### PR TITLE
Card components

### PR DESCRIPTION
**Pull request by kshitijthatte**
This PR apart from the card components also has some fixes in button padding and a new transparent button.

### CODE REVIEW

**Comment by msdeshmukh009** [comment]
The code is looking clean and readable the and UI components are also looking nice. 
Correct me if I'm wrong but I think you have missed the **card with the badge** component which is mentioned in the PRD.

**Review by sakshamAK — COMMENTED** [review]
Great work!! Really clean and nice cards.
But the close button card and badge card are missing

**Review by horsemaker — COMMENTED** [review]
The UI looks clean Kshitij & the code is also fine!
Other than the missing cards @msdeshmukh009 & @sakshamAK have mentioned, the cards look neat. 👌

**Review by tanveertkd — CHANGES_REQUESTED** [review]
Just have to add the cards mentioned above, apart from that this looks good to go!

**Review by MarkVed17 — APPROVED** [review]
The cards look really nice, Kshitij!
You’ve made them responsive too 👌🏼

**Comment by kshitijthatte** [comment]
> The code is looking clean and readable the and UI components are also looking nice. Correct me if I'm wrong but I think you have missed the **card with the badge** component which is mentioned in the PRD.

> Great work!! Really clean and nice cards. But the close button card and badge card are missing

> The UI looks clean Kshitij & the code is also fine! Other than the missing cards @msdeshmukh009 & @sakshamAK have mentioned, the cards look neat. 👌

> Just have to add the cards mentioned above, apart from that this looks good to go!

> The cards look really nice, Kshitij! You’ve made them responsive too 👌🏼

Thank you guys, earlier I couldn't understand the need for badge cards, but I got that now. Also, I thought I've made the action button cards and they could be used for dismissing, but now I've added both of them.

**Pull request merged**
