### PR TITLE
added landing page

### PR DESCRIPTION
**Pull request by kshitijthatte**

### CODE REVIEW

**Review by tanveertkd — APPROVED** [review]
This looks good! 
One suggestion though, you could play around with the font sizes for mobile screens other than that it looks really good!

**Comment by preethasri** [comment]
Awesome landing page.

**Review by preethasri — APPROVED** [review]
Awesome landing page

**Comment by kshitijthatte** [comment]
> This looks good! One suggestion though, you could play around with the font sizes for mobile screens other than that it looks really good!

Thanks for the suggestion Tanveer!

**Pull request merged**
